server:
  port: 8080
spring:
  application:
    name: translation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/translation?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: tiger
  jpa:
    database: mysql
    show-sql: true

